// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDazegqPBGYlNdSOmUtblwBd3reBZd4nyE',
    appId: '1:566519754434:web:9ce35adcb9812ec23e955b',
    messagingSenderId: '566519754434',
    projectId: 'ai-career-coach-app',
    authDomain: 'ai-career-coach-app.firebaseapp.com',
    storageBucket: 'ai-career-coach-app.firebasestorage.app',
    measurementId: 'G-YLGXGPJC7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5sgci7C3EJ49JDaUaEMiSuHtCQ4Rq5T0',
    appId: '1:566519754434:android:069477f052798ae83e955b',
    messagingSenderId: '566519754434',
    projectId: 'ai-career-coach-app',
    storageBucket: 'ai-career-coach-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgw0LC1ldKLl9sSMJjti7IDvxUStYNSJM',
    appId: '1:566519754434:ios:2281c0ac65442a103e955b',
    messagingSenderId: '566519754434',
    projectId: 'ai-career-coach-app',
    storageBucket: 'ai-career-coach-app.firebasestorage.app',
    iosClientId: '566519754434-bfskea4sn8nstq6vlakniujh8uduoism.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiCareerCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgw0LC1ldKLl9sSMJjti7IDvxUStYNSJM',
    appId: '1:566519754434:ios:2281c0ac65442a103e955b',
    messagingSenderId: '566519754434',
    projectId: 'ai-career-coach-app',
    storageBucket: 'ai-career-coach-app.firebasestorage.app',
    iosClientId: '566519754434-bfskea4sn8nstq6vlakniujh8uduoism.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiCareerCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDazegqPBGYlNdSOmUtblwBd3reBZd4nyE',
    appId: '1:566519754434:web:6b08f38bd6fa4c783e955b',
    messagingSenderId: '566519754434',
    projectId: 'ai-career-coach-app',
    authDomain: 'ai-career-coach-app.firebaseapp.com',
    storageBucket: 'ai-career-coach-app.firebasestorage.app',
    measurementId: 'G-WNCNDFRW2D',
  );
}
